/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ASSU API
 * ASSU API 紐낆꽭�꽌
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from "../../orvalMutator";
export interface BaseResponseGetStoreDetailsDTO {
	isSuccess?: boolean;
	code?: string;
	message?: string;
	result?: GetStoreDetailsDTO;
}

export interface GetStoreDetailsDTO {
	storeId?: number;
	storeName?: string;
	address?: string;
	detailAddress?: string;
	latitude?: number;
	longitude?: number;
	storeCategory?: string;
	rate?: number;
	phoneNumber?: string;
	hasPartner?: boolean;
	profileUrl?: string;
}

export const getAssuApi = () => {
	/**
 * # [v1.0 (2026-08-31)](https://clumsy-seeder-416.notion.site/3cd1197c19ed806eb1abce6ab4c5f4fb?source=copy_link)
- 媛�寃� ID濡� 媛�寃� �긽�꽭 �젙蹂대�� 議고쉶�빀�땲�떎.

**Path Variable:**
  - `storeId` (Long, required): 議고쉶�븷 媛�寃� ID

**Response (GetStoreDetailsDTO):**
  - `storeId` (Long): 媛�寃� 怨좎쑀 ID
  - `storeName` (String): 媛�寃� �씠由�
  - `address` (String): 媛�寃� 二쇱냼
  - `detailAddress` (String): 媛�寃� �긽�꽭 二쇱냼
  - `latitude` (Double): �쐞�룄
  - `longitude` (Double): 寃쎈룄
  - `storeCategory` (String): 媛�寃� 移댄뀒怨좊━
  - `rate` (Integer): 媛�寃� �룊�젏
  - `phoneNumber` (String): �뾽泥� �쟾�솕踰덊샇
  - `hasPartner` (Boolean): �젣�쑕�뾽泥� �뿬遺�
  - `profileUrl` (String): �뾽泥� �봽濡쒗븘 �씠誘몄�� presigned URL

**Error Cases:**
  - �꽦怨�: 200 OK
  - 404 NOT_FOUND: �빐�떦 媛�寃뚮�� 李얠쓣 �닔 �뾾�뒗 寃쎌슦
 * @summary 媛�寃� �긽�꽭 議고쉶 API
 */
	const getStoreDetails = (storeId: number) => {
		return customInstance<BaseResponseGetStoreDetailsDTO>({
			url: `/store/${storeId}`,
			method: "GET",
		});
	};

	return { getStoreDetails };
};
export type GetStoreDetailsResult = NonNullable<
	Awaited<ReturnType<ReturnType<typeof getAssuApi>["getStoreDetails"]>>
>;
