/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ASSU API
 * ASSU API 명세서
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from "../../orvalMutator";
/**
 * 채팅 차단 DTO
 */
export interface BlockMemberRequestDTO {
	/** 차단할 사용자 ID */
	opponentId?: number;
}

export interface BaseResponseBlockMemberDTO {
	isSuccess?: boolean;
	code?: string;
	message?: string;
	result?: BlockMemberDTO;
}

export interface BlockMemberDTO {
	memberId?: number;
	name?: string;
	blockDate?: string;
}

export const getAssuApi = () => {
	/**
 * # [v1.0 (2025-09-25)](https://clumsy-seeder-416.notion.site/2db1197c19ed804ba3dbf57ba36860c4)
- 상대방을 차단합니다.
- 메시지를 주고받을 수 없습니다.

**Request Body:**
- opponentId (Long, required): 상대방 ID

 * @summary 상대방 차단 API
 */
	const block = (blockMemberRequestDTO: BlockMemberRequestDTO) => {
		return customInstance<BaseResponseBlockMemberDTO>({
			url: `/chat/block`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: blockMemberRequestDTO,
		});
	};

	return { block };
};
export type BlockResult = NonNullable<
	Awaited<ReturnType<ReturnType<typeof getAssuApi>["block"]>>
>;
