/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ASSU API
 * ASSU API 명세서
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from "../../orvalMutator";
/**
 * 이메일 중복 확인 요청
 */
export interface EmailVerificationCheckRequestDTO {
	/** 확인할 이메일 주소 */
	email: string;
}

export type BaseResponseVoidResult = { [key: string]: unknown };

export interface BaseResponseVoid {
	isSuccess?: boolean;
	code?: string;
	message?: string;
	result?: BaseResponseVoidResult;
}

export const getAssuApi = () => {
	/**
 * # [v1.0 (2025-09-18)](https://clumsy-seeder-416.notion.site/2551197c19ed802d8f6dd373dd045f3a?source=copy_link)
- 입력한 이메일이 이미 가입된 사용자가 있는지 확인합니다.
- 중복된 이메일이 있으면 에러를 반환합니다.

**Request Body:**
  - `email` (String, required): 확인할 이메일 주소

**Response:**
  - 성공 시 200(OK)과 사용 가능 메시지 반환
  - 중복 시 404(NOT_FOUND)와 에러 메시지 반환
 * @summary 이메일 형식 및 중복가입 확인 API
 */
	const checkEmailAvailability = (
		emailVerificationCheckRequestDTO: EmailVerificationCheckRequestDTO,
	) => {
		return customInstance<BaseResponseVoid>({
			url: `/auth/email-verification/check`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: emailVerificationCheckRequestDTO,
		});
	};

	return { checkEmailAvailability };
};
export type CheckEmailAvailabilityResult = NonNullable<
	Awaited<ReturnType<ReturnType<typeof getAssuApi>["checkEmailAvailability"]>>
>;
