/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ASSU API
 * ASSU API 명세서
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from "../../orvalMutator";
/**
 * 휴대폰 인증번호 검증 요청
 */
export interface PhoneAuthVerifyRequestDTO {
	/**
	 * 인증받을 휴대폰 번호
	 * @pattern ^010\d{8}$
	 */
	phoneNumber: string;
	/** 발송받은 인증번호(OTP) */
	authNumber: string;
}

export type BaseResponseVoidResult = { [key: string]: unknown };

export interface BaseResponseVoid {
	isSuccess?: boolean;
	code?: string;
	message?: string;
	result?: BaseResponseVoidResult;
}

export const getAssuApi = () => {
	/**
 * # [v1.0 (2025-09-03)](https://clumsy-seeder-416.notion.site/2241197c19ed81bb8c05d9061c0306c0?source=copy_link)
- 발송된 인증번호(OTP)를 검증합니다.

**Request Body:**
  - `phoneNumber` (String, required): 인증받을 휴대폰 번호
  - `authNumber` (String, required): 발송받은 인증번호(OTP)

**Response:**
  - 성공 시 200(OK)과 성공 메시지 반환
 * @summary 휴대폰 인증번호 검증 API
 */
	const checkAuthNumber = (
		phoneAuthVerifyRequestDTO: PhoneAuthVerifyRequestDTO,
	) => {
		return customInstance<BaseResponseVoid>({
			url: `/auth/phone-verification/verify`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: phoneAuthVerifyRequestDTO,
		});
	};

	return { checkAuthNumber };
};
export type CheckAuthNumberResult = NonNullable<
	Awaited<ReturnType<ReturnType<typeof getAssuApi>["checkAuthNumber"]>>
>;
