/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ASSU API
 * ASSU API 명세서
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from "../../orvalMutator";
/**
 * 휴대폰 번호 중복가입 확인 및 인증번호 발송 요청
 */
export interface PhoneAuthSendRequestDTO {
	/**
	 * 인증번호를 받을 휴대폰 번호
	 * @pattern ^010\d{8}$
	 */
	phoneNumber: string;
}

export type BaseResponseVoidResult = { [key: string]: unknown };

export interface BaseResponseVoid {
	isSuccess?: boolean;
	code?: string;
	message?: string;
	result?: BaseResponseVoidResult;
}

export const getAssuApi = () => {
	/**
 * # [v1.1 (2025-09-25)](https://clumsy-seeder-416.notion.site/2241197c19ed801bbcd9f61c3e5f5457?source=copy_link)
- 입력한 휴대폰 번호로 1회용 인증번호(OTP)를 발송합니다.
- 중복된 전화번호가 있으면 에러를 반환합니다.
- 관리자와 제휴업체의 회원가입 이전에 사용하여 전화번호를 검증합니다.
- 유효시간/재요청 제한 정책은 서버 설정에 따릅니다.

**Request Body:**
  - `phoneNumber` (String, required): 인증번호를 받을 휴대폰 번호

**Response:**
  - 성공 시 200(OK)과 성공 메시지 반환
 * @summary 휴대폰 번호 중복가입 확인 및 인증번호 발송 API
 */
	const checkPhoneAvailabilityAndSendAuthNumber = (
		phoneAuthSendRequestDTO: PhoneAuthSendRequestDTO,
	) => {
		return customInstance<BaseResponseVoid>({
			url: `/auth/phone-verification/check-and-send`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: phoneAuthSendRequestDTO,
		});
	};

	return { checkPhoneAvailabilityAndSendAuthNumber };
};
export type CheckPhoneAvailabilityAndSendAuthNumberResult = NonNullable<
	Awaited<
		ReturnType<
			ReturnType<typeof getAssuApi>["checkPhoneAvailabilityAndSendAuthNumber"]
		>
	>
>;
