/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ASSU API
 * ASSU API 명세서
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from "../../orvalMutator";
export interface BaseResponseCheckBlockMemberDTO {
	isSuccess?: boolean;
	code?: string;
	message?: string;
	result?: CheckBlockMemberDTO;
}

export interface CheckBlockMemberDTO {
	memberId?: number;
	name?: string;
	blocked?: boolean;
}

export const getAssuApi = () => {
	/**
 * # [v1.0 (2025-09-25)](https://clumsy-seeder-416.notion.site/2db1197c19ed80769521eab9660ac53f)
- 상대방을 차단했는지 검사합니다.

**Path Variable:**
- opponentId (Long, required): 상대방 ID

 * @summary 상대방 차단 여부 확인 API
 */
	const checkBlock = (opponentId: number) => {
		return customInstance<BaseResponseCheckBlockMemberDTO>({
			url: `/chat/check/block/${opponentId}`,
			method: "GET",
		});
	};

	return { checkBlock };
};
export type CheckBlockResult = NonNullable<
	Awaited<ReturnType<ReturnType<typeof getAssuApi>["checkBlock"]>>
>;
