/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ASSU API
 * ASSU API 명세서
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from "../../orvalMutator";
/**
 * 채팅방 생성 요청 DTO
 */
export interface CreateChatRoomRequestDTO {
	/** 사장님 id */
	adminId?: number;
	/** 파트너 id */
	partnerId?: number;
}

export interface BaseResponseCreateChatRoomResponseDTO {
	isSuccess?: boolean;
	code?: string;
	message?: string;
	result?: CreateChatRoomResponseDTO;
}

export interface CreateChatRoomResponseDTO {
	roomId?: number;
	adminViewName?: string;
	partnerViewName?: string;
	isNew?: boolean;
}

export const getAssuApi = () => {
	/**
 * # [v1.0 (2025-08-05)](https://clumsy-seeder-416.notion.site/2241197c19ed80c38871ec77deced713)
- 채팅방을 생성합니다.

**Request Body:**
- adminId (Long, required): 관리자 ID
- partnerId (Long, required) 제휴업체 ID

 * @summary 채팅방 생성 API
 */
	const createChatRoom = (
		createChatRoomRequestDTO: CreateChatRoomRequestDTO,
	) => {
		return customInstance<BaseResponseCreateChatRoomResponseDTO>({
			url: `/chat/rooms`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: createChatRoomRequestDTO,
		});
	};

	return { createChatRoom };
};
export type CreateChatRoomResult = NonNullable<
	Awaited<ReturnType<ReturnType<typeof getAssuApi>["createChatRoom"]>>
>;
