/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ASSU API
 * ASSU API 명세서
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from "../../orvalMutator";
export interface BaseResponseListBlockMemberDTO {
	isSuccess?: boolean;
	code?: string;
	message?: string;
	result?: BlockMemberDTO[];
}

export interface BlockMemberDTO {
	memberId?: number;
	name?: string;
	blockDate?: string;
}

export const getAssuApi = () => {
	/**
 * # [v1.0 (2025-09-25)](https://clumsy-seeder-416.notion.site/2db1197c19ed8000b047d9857bcbbb2f)
- 차단한 대상을 조회합니다.

 * @summary 차단한 대상 조회 API
 */
	const getBlockList = () => {
		return customInstance<BaseResponseListBlockMemberDTO>({
			url: `/chat/block-list`,
			method: "GET",
		});
	};

	return { getBlockList };
};
export type GetBlockListResult = NonNullable<
	Awaited<ReturnType<ReturnType<typeof getAssuApi>["getBlockList"]>>
>;
