/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ASSU API
 * ASSU API 명세서
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from "../../orvalMutator";
export interface BaseResponseChatHistoryResponseDTO {
	isSuccess?: boolean;
	code?: string;
	message?: string;
	result?: ChatHistoryResponseDTO;
}

export interface ChatHistoryResponseDTO {
	roomId?: number;
	messages?: ChatMessageDTO[];
}

export type ChatMessageDTOMessageType =
	(typeof ChatMessageDTOMessageType)[keyof typeof ChatMessageDTOMessageType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChatMessageDTOMessageType = {
	TEXT: "TEXT",
	PROPOSAL: "PROPOSAL",
	SYSTEM: "SYSTEM",
	GUIDE: "GUIDE",
} as const;

export interface ChatMessageDTO {
	messageId?: number;
	message?: string;
	sendTime?: string;
	unreadCountForSender?: number;
	isRead?: boolean;
	isMyMessage?: boolean;
	messageType?: ChatMessageDTOMessageType;
}

export const getAssuApi = () => {
	/**
 * # [v1.0 (2025-08-05)](https://clumsy-seeder-416.notion.site/2241197c19ed800eab45c35073761c97?v=2241197c19ed8134b64f000cc26c5d31&p=2241197c19ed81399395fd66f73730af&pm=s)
- 채팅방을 클릭했을 때 메시지를 조회합니다.

**Path Variable:**
- roomId (Long, required): 채팅방 ID

 * @summary 채팅방 상세 조회 API
 */
	const getChatHistory = (roomId: number) => {
		return customInstance<BaseResponseChatHistoryResponseDTO>({
			url: `/chat/rooms/${roomId}/messages`,
			method: "GET",
		});
	};

	return { getChatHistory };
};
export type GetChatHistoryResult = NonNullable<
	Awaited<ReturnType<ReturnType<typeof getAssuApi>["getChatHistory"]>>
>;
