/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ASSU API
 * ASSU API 명세서
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from "../../orvalMutator";
export interface BaseResponseListChatRoomListResultDTO {
	isSuccess?: boolean;
	code?: string;
	message?: string;
	result?: ChatRoomListResultDTO[];
}

export interface ChatRoomListResultDTO {
	roomId?: number;
	lastMessage?: string;
	lastMessageTime?: string;
	unreadMessagesCount?: number;
	opponentId?: number;
	opponentName?: string;
	opponentProfileImage?: string;
	phoneNumber?: string;
}

export const getAssuApi = () => {
	/**
 * # [v1.0 (2025-08-05)](https://clumsy-seeder-416.notion.site/API-1d71197c19ed819f8f70fb437e9ce62b?p=2241197c19ed816993c3c5ae17d6f099&pm=s)
- 채팅방 목록을 조회합니다.

 * @summary 채팅방 목록 조회 API
 */
	const getChatRoomList = () => {
		return customInstance<BaseResponseListChatRoomListResultDTO>({
			url: `/chat/rooms`,
			method: "GET",
		});
	};

	return { getChatRoomList };
};
export type GetChatRoomListResult = NonNullable<
	Awaited<ReturnType<ReturnType<typeof getAssuApi>["getChatRoomList"]>>
>;
