/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ASSU API
 * ASSU API 명세서
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from "../../orvalMutator";
export interface BaseResponseNotificationSettingsResponseDTO {
	isSuccess?: boolean;
	code?: string;
	message?: string;
	result?: NotificationSettingsResponseDTO;
}

export type NotificationSettingsResponseDTOSettings = {
	[key: string]: boolean;
};

export interface NotificationSettingsResponseDTO {
	settings?: NotificationSettingsResponseDTOSettings;
}

export const getAssuApi = () => {
	/**
 * # [v1.0 (2025-09-02)](https://clumsy-seeder-416.notion.site/2691197c19ed80de9b92d96db3608cdf?source=copy_link)
- 현재 로그인 사용자의 알림 설정 상태를 반환합니다.
- 모든 알림 유형에 대한 ON/OFF 상태를 확인할 수 있습니다.

**Response:**
- 성공 시 200(OK)와 알림 설정 상태 반환
- 각 알림 유형별 true/false 값 포함
- 401(UNAUTHORIZED): 인증되지 않은 사용자
 * @summary 알림 현재 설정 조회 API
 */
	const getSettings = () => {
		return customInstance<BaseResponseNotificationSettingsResponseDTO>({
			url: `/notifications/settings`,
			method: "GET",
		});
	};

	return { getSettings };
};
export type GetSettingsResult = NonNullable<
	Awaited<ReturnType<ReturnType<typeof getAssuApi>["getSettings"]>>
>;
