/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ASSU API
 * ASSU API 명세서
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from "../../orvalMutator";
export interface BaseResponseLeaveChattingRoomResponseDTO {
	isSuccess?: boolean;
	code?: string;
	message?: string;
	result?: LeaveChattingRoomResponseDTO;
}

export interface LeaveChattingRoomResponseDTO {
	roomId?: number;
	isLeftSuccessfully?: boolean;
	isRoomDeleted?: boolean;
}

export const getAssuApi = () => {
	/**
 * # [v1.0 (2025-08-05)](https://clumsy-seeder-416.notion.site/2241197c19ed800eab45c35073761c97?v=2241197c19ed8134b64f000cc26c5d31&p=2371197c19ed8079a6e1c2331cb4f534&pm=s)
- 채팅방을 나갑니다.
- 참여자가 2명이면 채팅방이 살아있지만, 이미 한 명이 나갔다면 채팅방이 삭제됩니다.

**Path Variable:**
- roomId (Long, required): 채팅방 ID

 * @summary 채팅방 나가기 API
 */
	const leaveChattingRoom = (roomId: number) => {
		return customInstance<BaseResponseLeaveChattingRoomResponseDTO>({
			url: `/chat/rooms/${roomId}/leave`,
			method: "DELETE",
		});
	};

	return { leaveChattingRoom };
};
export type LeaveChattingRoomResult = NonNullable<
	Awaited<ReturnType<ReturnType<typeof getAssuApi>["leaveChattingRoom"]>>
>;
