/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ASSU API
 * ASSU API 명세서
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from "../../orvalMutator";
export type BaseResponseMapStringObjectResult = {
	[key: string]: { [key: string]: unknown };
};

export interface BaseResponseMapStringObject {
	isSuccess?: boolean;
	code?: string;
	message?: string;
	result?: BaseResponseMapStringObjectResult;
}

export type List1Params = {
	status?: string;
	page?: number;
	size?: number;
};

export const getAssuApi = () => {
	/**
 * # [v1.0 (2025-09-02)](https://www.notion.so/2491197c19ed8091b349ef0ef4bb0f60?source=copy_link)
- 본인의 알림 목록을 상태별로 조회합니다.

**Request Parameters:**
- `status` (String, optional): 알림 상태 (all, unread) - 기본값: all
- `page` (Integer, optional): 페이지 번호 (1 이상) - 기본값: 1
- `size` (Integer, optional): 페이지 크기 - 기본값: 20

**Response:**
- 성공 시 200(OK)과 알림 목록 반환
- 400(BAD_REQUEST): 잘못된 상태 값 또는 페이지 번호
- 401(UNAUTHORIZED): 인증되지 않은 사용자
 * @summary 알림 목록 조회 API
 */
	const list1 = (params?: List1Params) => {
		return customInstance<BaseResponseMapStringObject>({
			url: `/notifications`,
			method: "GET",
			params,
		});
	};

	return { list1 };
};
export type List1Result = NonNullable<
	Awaited<ReturnType<ReturnType<typeof getAssuApi>["list1"]>>
>;
