/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * ASSU API
 * ASSU API 명세서
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from "../../orvalMutator";
export interface InquiryResponseDTO {
	/** 문의 ID */
	id?: number;
	/** 문의 제목 */
	title?: string;
	/** 문의 내용 */
	content?: string;
	/** 문의자 이메일 */
	email?: string;
	/** 문의 상태 */
	status?: string;
	/** 답변 내용 */
	answer?: string;
	/** 문의 생성 일시 */
	createdAt?: string;
}

export interface PageResponseDTOInquiryResponseDTO {
	items?: InquiryResponseDTO[];
	page?: number;
	size?: number;
	totalPages?: number;
	totalElements?: number;
}

export interface BaseResponsePageResponseDTOInquiryResponseDTO {
	isSuccess?: boolean;
	code?: string;
	message?: string;
	result?: PageResponseDTOInquiryResponseDTO;
}

export type ListParams = {
	status?: ListStatus;
	/**
	 * @minimum 1
	 */
	page?: number;
	size?: number;
};

export type ListStatus = (typeof ListStatus)[keyof typeof ListStatus];

export const ListStatus = {
	WAITING: "WAITING",
	ANSWERED: "ANSWERED",
	ALL: "ALL",
} as const;

export const getAssuApi = () => {
	/**
	 * # [v1.0 (2025-09-02)](https://www.notion.so/2441197c19ed803eba4af9598484e5c5?source=copy_link)
	 * - 본인의 문의 내역 목록을 상태별로 조회합니다.
	 *
	 * **Request Parameters:**
	 * - `status` (String, optional): 문의 상태 (WAITING, ANSWERED, ALL) - 기본값: ALL
	 * - `page` (Integer, optional): 페이지 번호 (1 이상) - 기본값: 1
	 * - `size` (Integer, optional): 페이지 크기 - 기본값: 20
	 *
	 * **Response:**
	 * - 성공 시 200(OK)과 문의 목록 반환
	 * - 400(BAD_REQUEST): 잘못된 페이지 번호 또는 상태 값
	 * - 401(UNAUTHORIZED): 인증되지 않은 사용자
	 * @summary 문의 내역 목록 조회 API
	 */
	const list = (params?: ListParams) => {
		return customInstance<BaseResponsePageResponseDTOInquiryResponseDTO>({
			url: `/inquiries`,
			method: "GET",
			params,
		});
	};

	return { list };
};
export type ListResult = NonNullable<
	Awaited<ReturnType<ReturnType<typeof getAssuApi>["list"]>>
>;
