/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ASSU API
 * ASSU API 명세서
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from "../../orvalMutator";
/**
 * 대학교
 */
export type StudentTokenAuthPayloadDTOUniversity =
	(typeof StudentTokenAuthPayloadDTOUniversity)[keyof typeof StudentTokenAuthPayloadDTOUniversity];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StudentTokenAuthPayloadDTOUniversity = {
	SSU: "SSU",
} as const;

/**
 * 학생 토큰 인증 페이로드
 */
export interface StudentTokenAuthPayloadDTO {
	/** 유세인트 sToken */
	sToken: string;
	/** 유세인트 sIdno */
	sIdno: string;
	/** 대학교 */
	university?: StudentTokenAuthPayloadDTOUniversity;
}

export interface BaseResponseLoginResponseDTO {
	isSuccess?: boolean;
	code?: string;
	message?: string;
	result?: LoginResponseDTO;
}

/**
 * 회원 역할
 */
export type LoginResponseDTORole =
	(typeof LoginResponseDTORole)[keyof typeof LoginResponseDTORole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LoginResponseDTORole = {
	STUDENT: "STUDENT",
	ADMIN: "ADMIN",
	PARTNER: "PARTNER",
} as const;

/**
 * 회원 상태
 */
export type LoginResponseDTOStatus =
	(typeof LoginResponseDTOStatus)[keyof typeof LoginResponseDTOStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LoginResponseDTOStatus = {
	ACTIVE: "ACTIVE",
	INACTIVE: "INACTIVE",
	SUSPEND: "SUSPEND",
	BLANK: "BLANK",
} as const;

/**
 * 로그인 성공 응답
 */
export interface LoginResponseDTO {
	/** 회원 ID */
	memberId?: number;
	/** 회원 역할 */
	role?: LoginResponseDTORole;
	/** 회원 상태 */
	status?: LoginResponseDTOStatus;
	/** 액세스 토큰/리프레시 토큰 */
	tokens?: TokensDTO;
	/** 사용자 기본 정보 (캐싱용) */
	basicInfo?: UserBasicInfoDTO;
}

/**
 * JWT 토큰 정보
 */
export interface TokensDTO {
	/** 액세스 토큰 */
	accessToken?: string;
	/** 리프레시 토큰 */
	refreshToken?: string;
}

/**
 * 사용자 기본 정보
 */
export interface UserBasicInfoDTO {
	/** 이름/업체명/단체명 */
	name?: string;
	/** 대학교 */
	university?: string;
	/** 단과대 */
	department?: string;
	/** 전공/학과 */
	major?: string;
}

export const getAssuApi = () => {
	/**
 * # [v1.2 (2025-09-13)](https://clumsy-seeder-416.notion.site/2501197c19ed80f6b495fa37f8c084a8)
- `application/json`로 호출합니다.
- 바디: `StudentTokenAuthPayloadDTO(sToken, sIdno, university)`.
- 처리: 유세인트 인증 → 기존 회원 확인 → JWT 토큰 발급.
- 성공 시 200(OK)과 토큰(accessToken/refreshToken), 기본 정보 반환.

**Request Body:**
  - `StudentTokenAuthPayloadDTO` 객체 (JSON, required): 숭실대 학생 토큰 로그인 정보
  - `sToken` (String, required): 유세인트 sToken
  - `sIdno` (String, required): 유세인트 sIdno
  - `university` (University enum, required): 대학 이름 (SSU)

**Response:**
  - 성공 시 200(OK)과 `LoginResponseDTO` 객체 반환
  - `memberId` (Long): 회원 ID
  - `role` (UserRole): 회원 역할 (STUDENT)
  - `status` (ActivationStatus): 회원 상태
  - `tokens` (Object): JWT 토큰 정보 (accessToken, refreshToken)
  - `basicInfo` (UserBasicInfo): 사용자 기본 정보 (프론트 캐싱용)
    - `name` (String): 학생 이름
    - `university` (String): 대학교 (한글명)
    - `department` (String): 단과대 (한글명)
    - `major` (String): 전공/학과 (한글명)
 * @summary 학생 로그인 API
 */
	const loginStudent = (
		studentTokenAuthPayloadDTO: StudentTokenAuthPayloadDTO,
	) => {
		return customInstance<BaseResponseLoginResponseDTO>({
			url: `/auth/students/login`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: studentTokenAuthPayloadDTO,
		});
	};

	return { loginStudent };
};
export type LoginStudentResult = NonNullable<
	Awaited<ReturnType<ReturnType<typeof getAssuApi>["loginStudent"]>>
>;
