/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ASSU API
 * ASSU API 명세서
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from "../../orvalMutator";
import type { BaseResponseLoginResponseDTO } from "./loginStudent";

/**
 * 공통 로그인 요청
 */
export interface CommonLoginRequestDTO {
	/** 이메일 주소 */
	email: string;
	/** 비밀번호 */
	password: string;
}

export const getAssuApi = () => {
	/**
 * # [v1.1 (2025-09-13)](https://clumsy-seeder-416.notion.site/2241197c19ed811c961be6a474de0e50)
- `application/json`로 호출합니다.
- 바디: `CommonLoginRequestDTO(email, password)`.
- 처리: 자격 증명 검증 후 Access/Refresh 토큰 발급 및 저장.
- 성공 시 200(OK)과 토큰(accessToken/refreshToken), 기본 정보 반환.

**Request Body:**
  - `CommonLoginRequestDTO` 객체 (JSON, required): 로그인 정보
  - `email` (String, required): 이메일 주소
  - `password` (String, required): 비밀번호

**Response:**
  - 성공 시 200(OK)과 `LoginResponseDTO` 객체 반환
  - `memberId` (Long): 회원 ID
  - `role` (UserRole): 회원 역할 (PARTNER/ADMIN)
  - `status` (ActivationStatus): 회원 상태
  - `tokens` (Object): JWT 토큰 정보 (accessToken, refreshToken)
  - `basicInfo` (UserBasicInfo): 사용자 기본 정보 (프론트 캐싱용)
    - `name` (String): 업체명/단체명/관리자 이름
    - `university` (String): Admin인 경우 한글명, Partner인 경우 null
    - `department` (String): Admin인 경우 한글명, Partner인 경우 null
    - `major` (String): Admin인 경우 한글명, Partner인 경우 null
 * @summary 공통 로그인 API
 */
	const loginCommon = (commonLoginRequestDTO: CommonLoginRequestDTO) => {
		return customInstance<BaseResponseLoginResponseDTO>({
			url: `/auth/commons/login`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: commonLoginRequestDTO,
		});
	};

	return { loginCommon };
};
export type LoginCommonResult = NonNullable<
	Awaited<ReturnType<ReturnType<typeof getAssuApi>["loginCommon"]>>
>;
