/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ASSU API
 * ASSU API 명세서
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from "../../orvalMutator";
export interface BaseResponseString {
	isSuccess?: boolean;
	code?: string;
	message?: string;
	result?: string;
}

export const getAssuApi = () => {
	/**
 * # [v1.0 (2025-09-02)](https://www.notion.so/2491197c19ed80a89ff0c03bc150460f?source=copy_link)
- 알림 ID에 해당하는 알림을 읽음 처리합니다.
- 본인의 알림만 읽음 처리 가능합니다.

**Path Variable:**
- `notificationId` (Long, required): 알림 ID

**Response:**
- 성공 시 200(OK)과 성공 메시지 반환
- 401(UNAUTHORIZED): 인증되지 않은 사용자
- 403(FORBIDDEN): 다른 사용자의 알림 접근 시도
- 404(NOT_FOUND): 존재하지 않는 알림 ID
- 409(CONFLICT): 이미 읽음 처리된 알림
 * @summary 알림 읽음 처리 API
 */
	const markRead = (notificationId: number) => {
		return customInstance<BaseResponseString>({
			url: `/notifications/${notificationId}/read`,
			method: "POST",
		});
	};

	return { markRead };
};
export type MarkReadResult = NonNullable<
	Awaited<ReturnType<ReturnType<typeof getAssuApi>["markRead"]>>
>;
