/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ASSU API
 * ASSU API 명세서
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from "../../orvalMutator";
export interface BaseResponseReadMessageResponseDTO {
	isSuccess?: boolean;
	code?: string;
	message?: string;
	result?: ReadMessageResponseDTO;
}

export interface ReadMessageResponseDTO {
	roomId?: number;
	readerId?: number;
	readMessagesId?: number[];
	readCount?: number;
	isRead?: boolean;
}

export const getAssuApi = () => {
	/**
 * # [v1.0 (2025-08-05)](https://clumsy-seeder-416.notion.site/2241197c19ed800eab45c35073761c97?v=2241197c19ed8134b64f000cc26c5d31&p=2241197c19ed81ffa771cb18ab157b54&pm=s)
- 메시지를 읽음처리합니다.

**Path Variable:**
- roomId (Long, required): 채팅방 ID

 * @summary 메시지 읽음 처리 API
 */
	const readMessage = (roomId: number) => {
		return customInstance<BaseResponseReadMessageResponseDTO>({
			url: `/chat/rooms/${roomId}/read`,
			method: "PATCH",
		});
	};

	return { readMessage };
};
export type ReadMessageResult = NonNullable<
	Awaited<ReturnType<ReturnType<typeof getAssuApi>["readMessage"]>>
>;
