/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ASSU API
 * ASSU API 명세서
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from "../../orvalMutator";
export interface BaseResponseRefreshResponseDTO {
	isSuccess?: boolean;
	code?: string;
	message?: string;
	result?: RefreshResponseDTO;
}

/**
 * 액세스 토큰 갱신 응답
 */
export interface RefreshResponseDTO {
	/** 회원 ID */
	memberId?: number;
	/** 새로운 액세스 토큰 */
	newAccess?: string;
	/** 새로운 리프레시 토큰 */
	newRefresh?: string;
}

export const getAssuApi = () => {
	/**
 * # [v1.0 (2025-09-03)](https://clumsy-seeder-416.notion.site/2501197c19ed806ea8cff29f9cd8695a?source=copy_link)
- 헤더로 호출합니다.
- 헤더: `RefreshToken: <refreshToken>`.
- 처리: Refresh 검증/회전 후 신규 Access/Refresh 발급 및 저장.
- 성공 시 200(OK)과 신규 토큰 반환.

**Headers:**
  - `RefreshToken` (String, required): 리프레시 토큰

**Response:**
  - 성공 시 200(OK)과 `RefreshResponseDTO` 객체 반환
  - `memberId` (Long): 회원 ID
  - `newAccess` (String): 새로운 액세스 토큰
  - `newRefresh` (String): 새로운 리프레시 토큰
 * @summary Access Token 갱신 API
 */
	const refreshToken = () => {
		return customInstance<BaseResponseRefreshResponseDTO>({
			url: `/auth/tokens/refresh`,
			method: "POST",
		});
	};

	return { refreshToken };
};
export type RefreshTokenResult = NonNullable<
	Awaited<ReturnType<ReturnType<typeof getAssuApi>["refreshToken"]>>
>;
