/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ASSU API
 * ASSU API 명세서
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from "../../orvalMutator";
export interface BaseResponseLong {
	isSuccess?: boolean;
	code?: string;
	message?: string;
	result?: number;
}

export type RegisterParams = {
	token: string;
};

export const getAssuApi = () => {
	/**
 * # [v1.0 (2025-09-02)](https://www.notion.so/24e1197c19ed8092864ac5a1ddc88d07?source=copy_link)
- 디바이스 토큰을 등록하고 등록된 토큰의 ID를 반환합니다.
- 푸시 알림 수신을 위해 필수로 등록해야 합니다.

**Request Parameters:**
- `token` (String, required): FCM 디바이스 토큰

**Response:**
- 성공 시 200(OK)과 등록된 토큰 ID 반환
- 400(BAD_REQUEST): 빈 토큰 또는 잘못된 토큰 형식
- 401(UNAUTHORIZED): 인증되지 않은 사용자
- 409(CONFLICT): 이미 등록된 토큰
 * @summary 디바이스 토큰 등록 API
 */
	const register = (params: RegisterParams) => {
		return customInstance<BaseResponseLong>({
			url: `/device-tokens`,
			method: "POST",
			params,
		});
	};

	return { register };
};
export type RegisterResult = NonNullable<
	Awaited<ReturnType<ReturnType<typeof getAssuApi>["register"]>>
>;
