/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * ASSU API
 * ASSU API 명세서
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from "../../orvalMutator";
/**
 * 사용자 기본 정보
 */
export interface UserBasicInfoDTO {
	/** 단과대 */
	department?: string;
	/** 전공/학과 */
	major?: string;
	/** 이름/업체명/단체명 */
	name?: string;
	/** 대학교 */
	university?: string;
}

/**
 * JWT 토큰 정보
 */
export interface TokensDTO {
	/** 액세스 토큰 */
	accessToken?: string;
	/** 리프레시 토큰 */
	refreshToken?: string;
}

/**
 * 회원 상태
 */
export type SignUpResponseDTOStatus =
	(typeof SignUpResponseDTOStatus)[keyof typeof SignUpResponseDTOStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SignUpResponseDTOStatus = {
	ACTIVE: "ACTIVE",
	INACTIVE: "INACTIVE",
	SUSPEND: "SUSPEND",
	BLANK: "BLANK",
} as const;

/**
 * 회원 역할
 */
export type SignUpResponseDTORole =
	(typeof SignUpResponseDTORole)[keyof typeof SignUpResponseDTORole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SignUpResponseDTORole = {
	STUDENT: "STUDENT",
	ADMIN: "ADMIN",
	PARTNER: "PARTNER",
} as const;

/**
 * 회원가입 성공 응답
 */
export interface SignUpResponseDTO {
	/** 사용자 기본 정보 (캐싱용) */
	basicInfo?: UserBasicInfoDTO;
	/** 회원 ID */
	memberId?: number;
	/** 회원 역할 */
	role?: SignUpResponseDTORole;
	/** 회원 상태 */
	status?: SignUpResponseDTOStatus;
	/** 액세스 토큰/리프레시 토큰 */
	tokens?: TokensDTO;
}

export interface BaseResponseSignUpResponseDTO {
	code?: string;
	isSuccess?: boolean;
	message?: string;
	result?: SignUpResponseDTO;
}

/**
 * 대학교
 */
export type StudentTokenAuthPayloadDTOUniversity =
	(typeof StudentTokenAuthPayloadDTOUniversity)[keyof typeof StudentTokenAuthPayloadDTOUniversity];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StudentTokenAuthPayloadDTOUniversity = {
	SSU: "SSU",
} as const;

/**
 * 학생 토큰 인증 페이로드
 */
export interface StudentTokenAuthPayloadDTO {
	/** 유세인트 sIdno */
	sIdno: string;
	/** 유세인트 sToken */
	sToken: string;
	/** 대학교 */
	university?: StudentTokenAuthPayloadDTOUniversity;
}

/**
 * 학생 토큰 회원가입 요청
 */
export interface StudentTokenSignUpRequestDTO {
	/** 위치 정보 수집 동의 */
	locationAgree: boolean;
	/** 마케팅 수신 동의 */
	marketingAgree: boolean;
	/** 학생 토큰 인증 정보 */
	studentTokenAuth: StudentTokenAuthPayloadDTO;
}

export const getAssuApi = () => {
	/**
 * # [v1.3 (2026-04-02)](https://clumsy-seeder-416.notion.site/2241197c19ed81129c85cf5bbe1f7971)
- `application/json` 요청 바디를 사용합니다.
- 처리: 유세인트 인증 → 학생 정보 추출 → 회원가입 완료
- 성공 시 200(OK)과 생성된 memberId, JWT 토큰, 기본 정보 반환.

**Request Body:**
  - `StudentTokenSignUpRequestDTO` 객체 (JSON, required): 숭실대 학생 토큰 가입 정보
    - `marketingAgree` (Boolean, required): 마케팅 수신 동의
    - `locationAgree` (Boolean, required): 위치 정보 수집 동의
    - `studentTokenAuth` (StudentTokenAuthPayloadDTO, Object, required): 유세인트 토큰 정보
      - `sToken` (String, required): 유세인트 sToken
      - `sIdno` (String, required): 유세인트 sIdno
      - `university` (University enum, required): 대학 이름 (SSU)

**Response:**
  - 성공 시 200(OK)과 `SignUpResponseDTO` 객체 반환
  - `memberId` (Long): 회원 ID
  - `role` (UserRole): 회원 역할 (STUDENT)
  - `status` (ActivationStatus): 회원 상태 (ACTIVE)
  - `tokens` (Object): JWT 토큰 정보 (accessToken, refreshToken)
  - `basicInfo` (UserBasicInfo): 사용자 기본 정보 (프론트 캐싱용)
    - `name` (String): 학생 이름
    - `university` (String): 대학교 (한글명)
    - `department` (String): 단과대 (한글명)
    - `major` (String): 전공/학과 (한글명)
 * @summary 학생 회원가입 API
 */
	const signupStudent = (
		studentTokenSignUpRequestDTO: StudentTokenSignUpRequestDTO,
	) => {
		return customInstance<BaseResponseSignUpResponseDTO>({
			url: `/auth/students/signup`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: studentTokenSignUpRequestDTO,
		});
	};

	return { signupStudent };
};
export type SignupStudentResult = NonNullable<
	Awaited<ReturnType<ReturnType<typeof getAssuApi>["signupStudent"]>>
>;
