/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ASSU API
 * ASSU API 명세서
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from "../../orvalMutator";
/**
 * JSON 형식의 관리자 가입 정보
 */
export interface AdminSignUpRequestDTO {
	/**
	 * 휴대폰 번호
	 * @pattern ^(01[016789])\d{3,4}\d{4}$
	 */
	phoneNumber?: string;
	/** 마케팅 수신 동의 */
	marketingAgree: boolean;
	/** 위치 정보 수집 동의 */
	locationAgree: boolean;
	/** 관리자/제휴업체공통 인증 정보 */
	commonAuth: CommonAuthPayloadDTO;
	/** 관리자/제휴업체 공통 정보 */
	commonInfo: CommonInfoPayloadDTO;
}

/**
 * 단과대
 */
export type CommonAuthPayloadDTODepartment =
	(typeof CommonAuthPayloadDTODepartment)[keyof typeof CommonAuthPayloadDTODepartment];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommonAuthPayloadDTODepartment = {
	HUMANITIES: "HUMANITIES",
	NATURAL_SCIENCE: "NATURAL_SCIENCE",
	LAW: "LAW",
	SOCIAL_SCIENCE: "SOCIAL_SCIENCE",
	ECONOMICS: "ECONOMICS",
	BUSINESS: "BUSINESS",
	ENGINEERING: "ENGINEERING",
	IT: "IT",
	LIBERAL_STUDIES: "LIBERAL_STUDIES",
	AI: "AI",
} as const;

/**
 * 전공/학과
 */
export type CommonAuthPayloadDTOMajor =
	(typeof CommonAuthPayloadDTOMajor)[keyof typeof CommonAuthPayloadDTOMajor];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommonAuthPayloadDTOMajor = {
	CHRISTIAN_STUDIES: "CHRISTIAN_STUDIES",
	KOREAN_LITERATURE: "KOREAN_LITERATURE",
	ENGLISH_LITERATURE: "ENGLISH_LITERATURE",
	GERMAN_LITERATURE: "GERMAN_LITERATURE",
	FRENCH_LITERATURE: "FRENCH_LITERATURE",
	CHINESE_LITERATURE: "CHINESE_LITERATURE",
	JAPANESE_LITERATURE: "JAPANESE_LITERATURE",
	PHILOSOPHY: "PHILOSOPHY",
	HISTORY: "HISTORY",
	CREATIVE_ARTS: "CREATIVE_ARTS",
	SPORTS: "SPORTS",
	MATHEMATICS: "MATHEMATICS",
	CHEMISTRY: "CHEMISTRY",
	BIOMEDICAL_SYSTEMS: "BIOMEDICAL_SYSTEMS",
	PHYSICS: "PHYSICS",
	STATISTICS_ACTUARIAL: "STATISTICS_ACTUARIAL",
	LAW: "LAW",
	INTERNATIONAL_LAW: "INTERNATIONAL_LAW",
	SOCIAL_WELFARE: "SOCIAL_WELFARE",
	POLITICAL_SCIENCE: "POLITICAL_SCIENCE",
	MEDIA_COMMUNICATION: "MEDIA_COMMUNICATION",
	PUBLIC_ADMINISTRATION: "PUBLIC_ADMINISTRATION",
	INFORMATION_SOCIETY: "INFORMATION_SOCIETY",
	LIFELONG_EDUCATION: "LIFELONG_EDUCATION",
	ECONOMICS: "ECONOMICS",
	FINANCIAL_ECONOMICS: "FINANCIAL_ECONOMICS",
	GLOBAL_TRADE: "GLOBAL_TRADE",
	INTERNATIONAL_TRADE: "INTERNATIONAL_TRADE",
	BUSINESS_ADMINISTRATION: "BUSINESS_ADMINISTRATION",
	ACCOUNTING: "ACCOUNTING",
	VENTURE_MANAGEMENT: "VENTURE_MANAGEMENT",
	WELFARE_MANAGEMENT: "WELFARE_MANAGEMENT",
	VENTURE_SME: "VENTURE_SME",
	FINANCE: "FINANCE",
	INNOVATION_MANAGEMENT: "INNOVATION_MANAGEMENT",
	ACCOUNTING_TAX: "ACCOUNTING_TAX",
	CHEMICAL_ENGINEERING: "CHEMICAL_ENGINEERING",
	ELECTRICAL_ENGINEERING: "ELECTRICAL_ENGINEERING",
	ARCHITECTURE: "ARCHITECTURE",
	INDUSTRIAL_INFO_SYSTEMS: "INDUSTRIAL_INFO_SYSTEMS",
	MECHANICAL_ENGINEERING: "MECHANICAL_ENGINEERING",
	MATERIALS_SCIENCE: "MATERIALS_SCIENCE",
	SOFTWARE: "SOFTWARE",
	GLOBAL_MEDIA: "GLOBAL_MEDIA",
	COMPUTER_SCIENCE: "COMPUTER_SCIENCE",
	ELECTRONIC_ENGINEERING: "ELECTRONIC_ENGINEERING",
	AI_CONVERGENCE: "AI_CONVERGENCE",
	DIGITAL_MEDIA: "DIGITAL_MEDIA",
	LIBERAL_STUDIES: "LIBERAL_STUDIES",
	AI_SOFTWARE: "AI_SOFTWARE",
	INFORMATION_SECURITY: "INFORMATION_SECURITY",
} as const;

/**
 * 대학교
 */
export type CommonAuthPayloadDTOUniversity =
	(typeof CommonAuthPayloadDTOUniversity)[keyof typeof CommonAuthPayloadDTOUniversity];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommonAuthPayloadDTOUniversity = {
	SSU: "SSU",
} as const;

/**
 * 공통 인증 정보 페이로드
 */
export interface CommonAuthPayloadDTO {
	/** 이메일 주소 */
	email: string;
	/**
	 * 비밀번호(평문)
	 * @minLength 8
	 * @maxLength 72
	 */
	password: string;
	/** 단과대 */
	department?: CommonAuthPayloadDTODepartment;
	/** 전공/학과 */
	major?: CommonAuthPayloadDTOMajor;
	/** 대학교 */
	university?: CommonAuthPayloadDTOUniversity;
}

/**
 * 공통 정보 페이로드
 */
export interface CommonInfoPayloadDTO {
	/**
	 * 이름/업체명/단체명
	 * @minLength 1
	 * @maxLength 50
	 */
	name: string;
	/**
	 * 상세 주소
	 * @minLength 0
	 * @maxLength 255
	 */
	detailAddress?: string;
	/** 선택된 장소 정보 */
	selectedPlace: SelectedPlacePayload;
}

export interface SelectedPlacePayload {
	/** 장소 ID */
	placeId?: string;
	/** 장소 이름 */
	name?: string;
	/** 장소 지번 주소 */
	address?: string;
	/** 장소 도로명 주소 */
	roadAddress?: string;
	/** 장소 위도 */
	latitude?: number;
	/** 장소 경도 */
	longitude?: number;
}

export interface BaseResponseSignUpResponseDTO {
	isSuccess?: boolean;
	code?: string;
	message?: string;
	result?: SignUpResponseDTO;
}

/**
 * 회원 역할
 */
export type SignUpResponseDTORole =
	(typeof SignUpResponseDTORole)[keyof typeof SignUpResponseDTORole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SignUpResponseDTORole = {
	STUDENT: "STUDENT",
	ADMIN: "ADMIN",
	PARTNER: "PARTNER",
} as const;

/**
 * 회원 상태
 */
export type SignUpResponseDTOStatus =
	(typeof SignUpResponseDTOStatus)[keyof typeof SignUpResponseDTOStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SignUpResponseDTOStatus = {
	ACTIVE: "ACTIVE",
	INACTIVE: "INACTIVE",
	SUSPEND: "SUSPEND",
	BLANK: "BLANK",
} as const;

/**
 * 회원가입 성공 응답
 */
export interface SignUpResponseDTO {
	/** 회원 ID */
	memberId?: number;
	/** 회원 역할 */
	role?: SignUpResponseDTORole;
	/** 회원 상태 */
	status?: SignUpResponseDTOStatus;
	/** 액세스 토큰/리프레시 토큰 */
	tokens?: TokensDTO;
	/** 사용자 기본 정보 (캐싱용) */
	basicInfo?: UserBasicInfoDTO;
}

/**
 * JWT 토큰 정보
 */
export interface TokensDTO {
	/** 액세스 토큰 */
	accessToken?: string;
	/** 리프레시 토큰 */
	refreshToken?: string;
}

/**
 * 사용자 기본 정보
 */
export interface UserBasicInfoDTO {
	/** 이름/업체명/단체명 */
	name?: string;
	/** 대학교 */
	university?: string;
	/** 단과대 */
	department?: string;
	/** 전공/학과 */
	major?: string;
}

export type SignupAdminBody = {
	request: AdminSignUpRequestDTO;
	/** 인감 이미지 파일 (Multipart Part) */
	signImage: Blob;
};

export const getAssuApi = () => {
	/**
 * # [v1.2 (2025-09-13)](https://clumsy-seeder-416.notion.site/2501197c19ed80cdb98bc2b4d5042b48)
- `multipart/form-data`로 호출합니다.
- 파트: `request`(JSON, AdminSignUpRequestDTO) + `signImage`(파일, 신분증).
- 처리: users + common_auth 생성, 이메일 중복/비밀번호 규칙 검증.
- 성공 시 200(OK)과 생성된 memberId, JWT 토큰, 기본 정보 반환.

**Request Parts:**
  - `request` (JSON, required): `AdminSignUpRequestDTO` 객체
    - `phoneNumber` (String, required): 휴대폰 번호
    - `marketingAgree` (Boolean, required): 마케팅 수신 동의
    - `locationAgree` (Boolean, required): 위치 정보 수집 동의
    - `commonAuth` (CommonAuthPayloadDTO, required): 이메일/비밀번호 및 인증 관련 정보
      - `email` (String, required): 이메일 주소
      - `password` (String, required): 비밀번호(평문)
      - `university` (University enum, required): 대학교 Enum
      - `department` (Department enum, required): 단과대 Enum
      - `major` (Major enum, required): 전공 Enum
    - `commonInfo` (CommonInfoPayloadDTO, required): 사용자 기본 정보
      - `name` (String, required): 단체명/관리자 이름
      - `detailAddress` (String, required): 상세 주소
      - `selectedPlace` (SelectedPlacePayload, required): 선택된 장소 정보
        - `placeId` (String, required): 장소 ID
        - `name` (String, required): 장소 이름
        - `address` (String, required): 장소 지번 주소
        - `roadAddress` (String, required): 장소 도로명 주소
        - `latitude` (Double, required): 장소 위도
        - `longitude` (Double, required): 장소 경도
  - `signImage` (MultipartFile, required): 인감 이미지 파일

**Response:**
  - 성공 시 200(OK)과 `SignUpResponseDTO` 객체 반환
  - `memberId` (Long): 회원 ID
  - `role` (UserRole): 회원 역할 (ADMIN)
  - `status` (ActivationStatus): 회원 상태 (ACTIVE)
  - `tokens` (Object): JWT 토큰 정보 (accessToken, refreshToken)
  - `basicInfo` (UserBasicInfo): 사용자 기본 정보 (프론트 캐싱용)
    - `name` (String): 단체명/관리자 이름
    - `university` (String): 대학교 (한글명)
    - `department` (String): 단과대 (한글명)
    - `major` (String): 전공/학과 (한글명)
 * @summary 관리자 회원가입 API
 */
	const signupAdmin = (signupAdminBody: SignupAdminBody) => {
		const formData = new FormData();
		formData.append(`request`, JSON.stringify(signupAdminBody.request));
		formData.append(`signImage`, signupAdminBody.signImage);

		return customInstance<BaseResponseSignUpResponseDTO>({
			url: `/auth/admins/signup`,
			method: "POST",
			headers: { "Content-Type": "multipart/form-data" },
			data: formData,
		});
	};

	return { signupAdmin };
};
export type SignupAdminResult = NonNullable<
	Awaited<ReturnType<ReturnType<typeof getAssuApi>["signupAdmin"]>>
>;
