/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * ASSU API
 * ASSU API 명세서
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from "../../orvalMutator";
/**
 * 유세인트 인증 응답
 */
export interface USaintAuthResponseDTO {
	/** 학적 상태 */
	enrollmentStatus?: string;
	/** 전공/학과 */
	majorStr?: string;
	/** 이름 */
	name?: string;
	/** 학번 */
	studentNumber?: string;
	/** 학년/학기 */
	yearSemester?: string;
}

export interface BaseResponseUSaintAuthResponseDTO {
	code?: string;
	isSuccess?: boolean;
	message?: string;
	result?: USaintAuthResponseDTO;
}

/**
 * 유세인트 인증 요청
 */
export interface USaintAuthRequestDTO {
	/** 유세인트 sIdno */
	sIdno: string;
	/** 유세인트 sToken */
	sToken: string;
}

export const getAssuApi = () => {
	/**
 * # [v1.0 (2025-09-03)](https://clumsy-seeder-416.notion.site/23a1197c19ed808d9266e641e5c4ea14?source=copy_link)
- `application/json`으로 호출합니다.

**Request Body:**
  - `sToken` (String, required): 유세인트 sToken
  - `sIdno` (String, required): 유세인트 sIdno
- 처리 순서:
  1) 유세인트 SSO 로그인 시도 (sToken, sIdno 검증)
  2) 응답 Body 검증 후 세션 쿠키 추출
  3) 유세인트 포털 페이지 접근 및 HTML 파싱
  4) 이름, 학번, 소속, 학적 상태, 학년/학기 정보 추출
  5) 소속 문자열을 전공 Enum(`Major`)으로 매핑
  6) 인증 결과를 `USaintAuthResponseDTO`로 반환

**Response:**
  - 성공 시 200(OK)과 `USaintAuthResponseDTO` 객체 반환
  - `studentNumber` (String): 학번
  - `name` (String): 이름
  - `enrollmentStatus` (String): 학적 상태
  - `yearSemester` (String): 학년/학기
  - `major` (Major enum): 전공/학과
 * @summary 숭실대 유세인트 인증 API
 */
	const ssuAuth = (uSaintAuthRequestDTO: USaintAuthRequestDTO) => {
		return customInstance<BaseResponseUSaintAuthResponseDTO>({
			url: `/auth/students/ssu-verify`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: uSaintAuthRequestDTO,
		});
	};

	return { ssuAuth };
};
export type SsuAuthResult = NonNullable<
	Awaited<ReturnType<ReturnType<typeof getAssuApi>["ssuAuth"]>>
>;
