/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ASSU API
 * ASSU API 명세서
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from "../../orvalMutator";
export interface BaseResponseNotificationSettingsResponseDTO {
	isSuccess?: boolean;
	code?: string;
	message?: string;
	result?: NotificationSettingsResponseDTO;
}

export type NotificationSettingsResponseDTOSettings = {
	[key: string]: boolean;
};

export interface NotificationSettingsResponseDTO {
	settings?: NotificationSettingsResponseDTOSettings;
}

export const getAssuApi = () => {
	/**
 * # [v1.0 (2025-09-02)](https://www.notion.so/on-off-2511197c19ed80aeb4eed3c502691361?source=copy_link)
- 토글 형식으로 유형별 알림을 ON/OFF 합니다.
- 그룹 토글 기능을 지원합니다.

**Path Variable:**
- `type` (NotificationType, required): 알림 유형
  - 개별 유형: CHAT, PARTNER_SUGGESTION, PARTNER_PROPOSAL, ORDER, STAMP
  - 그룹 유형: PARTNER_ALL (CHAT + ORDER), ADMIN_ALL (CHAT + PARTNER_SUGGESTION + PARTNER_PROPOSAL)

**Response:**
- 성공 시 200(OK)와 변경된 알림 설정 상태 반환
- 400(BAD_REQUEST): 지원하지 않는 알림 유형
- 401(UNAUTHORIZED): 인증되지 않은 사용자
 * @summary 알림 유형별 ON/OFF 토글 API
 */
	const toggle = (
		type:
			| "CHAT"
			| "PARTNER_SUGGESTION"
			| "PARTNER_PROPOSAL"
			| "ORDER"
			| "PARTNER_ALL"
			| "ADMIN_ALL"
			| "STAMP",
	) => {
		return customInstance<BaseResponseNotificationSettingsResponseDTO>({
			url: `/notifications/${type}`,
			method: "PUT",
		});
	};

	return { toggle };
};
export type ToggleResult = NonNullable<
	Awaited<ReturnType<ReturnType<typeof getAssuApi>["toggle"]>>
>;
