/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ASSU API
 * ASSU API 명세서
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from "../../orvalMutator";
export interface BaseResponseBlockMemberDTO {
	isSuccess?: boolean;
	code?: string;
	message?: string;
	result?: BlockMemberDTO;
}

export interface BlockMemberDTO {
	memberId?: number;
	name?: string;
	blockDate?: string;
}

export type UnblockParams = {
	opponentId: number;
};

export const getAssuApi = () => {
	/**
 * # [v1.0 (2025-09-25)](https://clumsy-seeder-416.notion.site/2db1197c19ed80b6a93fcbe277fc934c?pvs=74)
- 상대방을 차단 해제합니다. 다시 메시지를 주고받을 수 있습니다.

**Request Parameter:**
- opponentId (Long, required): 상대방 ID

 * @summary 상대방 차단 해제 API
 */
	const unblock = (params: UnblockParams) => {
		return customInstance<BaseResponseBlockMemberDTO>({
			url: `/chat/unblock`,
			method: "DELETE",
			params,
		});
	};

	return { unblock };
};
export type UnblockResult = NonNullable<
	Awaited<ReturnType<ReturnType<typeof getAssuApi>["unblock"]>>
>;
