/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ASSU API
 * ASSU API 명세서
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from "../../orvalMutator";
export interface BaseResponseString {
	isSuccess?: boolean;
	code?: string;
	message?: string;
	result?: string;
}

export const getAssuApi = () => {
	/**
 * # [v1.0 (2025-09-02)](https://www.notion.so/24e1197c19ed80b8b26be9e01d24c929?source=copy_link)
- 로그아웃/탈퇴 시 호출해 디바이스 토큰 등록을 해제합니다.
- 자신의 토큰만 해제가 가능합니다.

**Path Variable:**
- `tokenId` (Long, required): 해제할 디바이스 토큰 ID

**Response:**
- 성공 시 200(OK)과 성공 메시지 반환
- 401(UNAUTHORIZED): 인증되지 않은 사용자
- 403(FORBIDDEN): 다른 사용자의 토큰 해제 시도
- 404(NOT_FOUND): 존재하지 않는 토큰 ID
 * @summary 디바이스 토큰 등록 해제 API
 */
	const unregister = (tokenId: number) => {
		return customInstance<BaseResponseString>({
			url: `/device-tokens/${tokenId}`,
			method: "DELETE",
		});
	};

	return { unregister };
};
export type UnregisterResult = NonNullable<
	Awaited<ReturnType<ReturnType<typeof getAssuApi>["unregister"]>>
>;
