/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ASSU API
 * ASSU API 명세서
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from "../../orvalMutator";
export interface BaseResponseStudentHomeResponseDTO {
	isSuccess?: boolean;
	code?: string;
	message?: string;
	result?: StudentHomeResponseDTO;
}

export interface StudentHomeResponseDTO {
	/** 상단 추천 업체 및 할인 정보 */
	featuredRecommendation?: FeaturedRecommendationDTO;
	/** 큐레이션 섹션 제목 (학생 이름 적용 완료) */
	curationTitle?: string;
	/** 추천 업체 그룹 목록 (총 2개 리스트, 각 리스트당 2개 업체) */
	curationLists?: CurationGroupDTO[];
}

export interface FeaturedRecommendationDTO {
	/** 추천 업체 ID */
	storeId?: number;
	/** 추천 업체 이름 */
	storeName?: string;
	/** 추천 할인 내용 */
	discountContent?: string;
	/** 업체 카테고리 */
	storeCategory?: string;
	/** 업체 프로필 이미지 URL */
	profileImageUrl?: string;
}

export interface CurationGroupDTO {
	/** 그룹 인덱스 (1 또는 2) */
	groupIndex?: number;
	/** 그룹 소제목 */
	groupTitle?: string;
	/** 그룹 내 추천 업체 목록 (2개) */
	stores?: CurationStoreDTO[];
}

export interface CurationStoreDTO {
	/** 가게 ID */
	storeId?: number;
	/** 가게 이름 */
	storeName?: string;
	/** 할인 및 혜택 내용 */
	discountContent?: string;
	/** 가게 카테고리 */
	storeCategory?: string;
	/** 가게 프로필 이미지 URL */
	profileImageUrl?: string;
}

export const getAssuApi = () => {
	/**
 * - 학생 홈 화면에 노출될 상단 추천 제휴(추천 업체/할인 내용) 및 맞춤형 큐레이션 리스트(2개 그룹 x 2개 업체)를 조회합니다.
- 큐레이션 섹션 제목의 {name}은 로그인한 학생의 이름으로 자동 치환되어 반환됩니다.

**Response:**
- 성공 시 200(OK)와 큐레이션 추천 정보(`StudentHomeResponseDTO`) 반환
- 401(UNAUTHORIZED): 인증되지 않은 사용자
- 404(NOT_FOUND): 학생 정보를 찾을 수 없음
 * @summary 학생 맞춤 큐레이션 추천 제휴 조회 API
 */
	const getRecommendCuration = () => {
		return customInstance<BaseResponseStudentHomeResponseDTO>({
			url: `/students/recommend/curation`,
			method: "GET",
		});
	};

	return { getRecommendCuration };
};
export type GetRecommendCurationResult = NonNullable<
	Awaited<ReturnType<ReturnType<typeof getAssuApi>["getRecommendCuration"]>>
>;
