/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ASSU API
 * ASSU API 명세서
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from "../../orvalMutator";
export interface BaseResponseListRecommendCarouselDTO {
	isSuccess?: boolean;
	code?: string;
	message?: string;
	result?: RecommendCarouselDTO[];
}

export interface RecommendCarouselDTO {
	category?: string;
	belonging?: string;
	partnerProfileUrl?: string;
	partnerName?: string;
	storeId?: number;
}

export const getAssuApi = () => {
	/**
 * # [v1.0 (2026-08-31)](https://clumsy-seeder-416.notion.site/3cd1197c19ed800b86f5ed255f91caf1?source=copy_link)
- 현재 로그인한 사용자가 이용 가능한 제휴 중 최대 14개를 랜덤으로 반환합니다.
- 활성 상태인 제휴만 포함됩니다.

**Response:**
- 성공 시 200(OK)와 추천 제휴 목록(최대 14개) 반환
- 401(UNAUTHORIZED): 인증되지 않은 사용자
- 404(NOT_FOUND): 사용자 정보를 찾을 수 없음
 * @summary 사용자의 추천 제휴 조회 API
 */
	const getRecommendCarouselPartnership = () => {
		return customInstance<BaseResponseListRecommendCarouselDTO>({
			url: `/students/recommend/carousel`,
			method: "GET",
		});
	};

	return { getRecommendCarouselPartnership };
};
export type GetRecommendCarouselPartnershipResult = NonNullable<
	Awaited<
		ReturnType<ReturnType<typeof getAssuApi>["getRecommendCarouselPartnership"]>
	>
>;
