/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ASSU API
 * ASSU API 紐낆꽭�꽌
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from "../../orvalMutator";
export interface BaseResponseListRecommendCarouselDTO {
	isSuccess?: boolean;
	code?: string;
	message?: string;
	result?: RecommendCarouselDTO[];
}

export interface RecommendCarouselDTO {
	category?: string;
	partnerProfileUrl?: string;
	partnerName?: string;
	storeId?: number;
}

export const getAssuApi = () => {
	/**
 * # [v1.0 (2026-08-31)](https://clumsy-seeder-416.notion.site/3cd1197c19ed800b86f5ed255f91caf1?source=copy_link)
- �쁽�옱 濡쒓렇�씤�븳 �궗�슜�옄媛� �씠�슜 媛��뒫�븳 �젣�쑕 以� 理쒕�� 14媛쒕�� �옖�뜡�쑝濡� 諛섑솚�빀�땲�떎.
- �솢�꽦 �긽�깭�씤 �젣�쑕留� �룷�븿�맗�땲�떎.

**Response:**
- �꽦怨� �떆 200(OK)��� 異붿쿇 �젣�쑕 紐⑸줉(理쒕�� 14媛�) 諛섑솚
- 401(UNAUTHORIZED): �씤利앸릺吏� �븡��� �궗�슜�옄
- 404(NOT_FOUND): �궗�슜�옄 �젙蹂대�� 李얠쓣 �닔 �뾾�쓬
 * @summary �궗�슜�옄�쓽 異붿쿇 �젣�쑕 議고쉶 API
 */
	const getRecommendCarouselPartnership = () => {
		return customInstance<BaseResponseListRecommendCarouselDTO>({
			url: `/students/recommend/carousel`,
			method: "GET",
		});
	};

	return { getRecommendCarouselPartnership };
};
export type GetRecommendCarouselPartnershipResult = NonNullable<
	Awaited<
		ReturnType<ReturnType<typeof getAssuApi>["getRecommendCarouselPartnership"]>
	>
>;
