/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ASSU API
 * ASSU API 紐낆꽭�꽌
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from "../../orvalMutator";
export interface BaseResponseListUsablePartnershipDTO {
	isSuccess?: boolean;
	code?: string;
	message?: string;
	result?: UsablePartnershipDTO[];
}

export type UsablePartnershipDTOCriterionType =
	(typeof UsablePartnershipDTOCriterionType)[keyof typeof UsablePartnershipDTOCriterionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsablePartnershipDTOCriterionType = {
	PRICE: "PRICE",
	HEADCOUNT: "HEADCOUNT",
} as const;

export type UsablePartnershipDTOOptionType =
	(typeof UsablePartnershipDTOOptionType)[keyof typeof UsablePartnershipDTOOptionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsablePartnershipDTOOptionType = {
	SERVICE: "SERVICE",
	DISCOUNT: "DISCOUNT",
} as const;

export interface UsablePartnershipDTO {
	partnershipId?: number;
	adminName?: string;
	partnerName?: string;
	criterionType?: UsablePartnershipDTOCriterionType;
	optionType?: UsablePartnershipDTOOptionType;
	people?: number;
	cost?: number;
	note?: string;
	paperId?: number;
	category?: string;
	discountRate?: number;
	storeId?: number;
	extraCount?: number;
	partnerProfileUrl?: string;
}

export type GetUsablePartnershipParams = {
	all?: boolean;
	storeCategory?: GetUsablePartnershipStoreCategory;
	adminId?: number;
};

export type GetUsablePartnershipStoreCategory =
	(typeof GetUsablePartnershipStoreCategory)[keyof typeof GetUsablePartnershipStoreCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUsablePartnershipStoreCategory = {
	RESTAURANT: "RESTAURANT",
	CAFE: "CAFE",
	BAR: "BAR",
	BEAUTY: "BEAUTY",
	ENTERTAINMENT: "ENTERTAINMENT",
	SPORTS: "SPORTS",
	LIVING: "LIVING",
	HOSPITAL: "HOSPITAL",
	EDUCATION: "EDUCATION",
	OTHERS: "OTHERS",
} as const;

export const getAssuApi = () => {
	/**
 * # [v1.1 (2026-08-31)](https://clumsy-seeder-416.notion.site/API-29c1197c19ed8030b1f5e2a744416651?source=copy_link)
- �쁽�옱 濡쒓렇�씤�븳 �궗�슜�옄媛� �씠�슜 媛��뒫�븳 �젣�쑕 紐⑸줉�쓣 議고쉶�빀�땲�떎.
- �솢�꽦 �긽�깭�씤 �젣�쑕留� 諛섑솚�빀�땲�떎.

**Request Parameters:**
- `all` (Boolean, optional): �쟾泥� 議고쉶 �뿬遺� - 湲곕낯媛�: false
  - true: 紐⑤뱺 �씠�슜 媛��뒫�븳 �젣�쑕 議고쉶
  - false: 理쒕�� 2媛쒕쭔 議고쉶
- `storeCategory` (StoreCategory, optional): 移댄뀒怨좊━ �븘�꽣 - 誘몄엯�젰 �떆 �쟾泥� 議고쉶

**Response:**
- �꽦怨� �떆 200(OK)��� �씠�슜 媛��뒫�븳 �젣�쑕 紐⑸줉 諛섑솚
- 401(UNAUTHORIZED): �씤利앸릺吏� �븡��� �궗�슜�옄
- 404(NOT_FOUND): �궗�슜�옄 �젙蹂대�� 李얠쓣 �닔 �뾾�쓬
 * @summary �궗�슜�옄�쓽 �씠�슜 媛��뒫�븳 �젣�쑕 議고쉶 API
 */
	const getUsablePartnership = (params?: GetUsablePartnershipParams) => {
		return customInstance<BaseResponseListUsablePartnershipDTO>({
			url: `/students/usable`,
			method: "GET",
			params,
		});
	};

	return { getUsablePartnership };
};
export type GetUsablePartnershipResult = NonNullable<
	Awaited<ReturnType<ReturnType<typeof getAssuApi>["getUsablePartnership"]>>
>;
